### PR TITLE
increase cutoff energy and charge density values in graphene example

### PR DESCRIPTION
**Pull request by Kenounouh**
Hello there is a problem with the ecutwfc value. I think, it shoulg be increased. Also I tried the lines of cade you gave for the pdos calculations, but it doesn't works for graphene and I dont really know why. I have a out of index error.

you really did a great job and this really helped me thanks a lot. Wah.

### CODE REVIEW

**Comment by pranabdas** [comment]
@Kenounouh hi, it is possible that the cutoff values are not optimal. You need to test convergence against cutoff energy and choose right values. I ran a quick test, I am getting similar results as presented. What problem are you exactly facing? Did you use the same [pseudo potential](http://pseudopotentials.quantum-espresso.org/upf_files/C.pbe-rrkjus.UPF)? Which version of QE are you running? Can you please repeat the calculations after clearing out previous output files (including the ones under `outdir` as specified in your input files)?

**Comment by Kenounouh** [comment]
Hi,
I am still a beginner as you may have noticed. I am using QE v7.1 and
Spyder/jupyter notebook.
yes I ran the convergence test. and I saw that the right value for ecutwfc
should be 40Ry as you can see in 'ecutwfc_conv.png' below.

I tried to do the pdos for graphene but I am unable to do so. I have some
index range issues and I am unable to point out what's wrong.
Here attached are my codes. The one named 'Gr_pdos_dat.py' is exactly what
you did in the previous calculations. and 'wah_project.py' is the one I did
with some few modifications. But when I do it I obtain 'Fig1'  which is not
really what I want so can you have a look and help me?
Here is my email address and I would like us to discuss more if you have
time or if interested in doing so.
***@***.***

Kind regards,
Wah.

**Comment by pranabdas** [comment]
@Kenounouh could you please send the attachments directly to my email, as the attachments you sent to github is not visible. You can find my email address on my [homepage](https://pranabdas.github.io). Thanks you.

**Comment by Kenounouh** [comment]
Ok

**Comment by Kenounouh** [comment]
Hello Pranab Das,
I am unable to find your mail on the home page

**Pull request merged**
